project_name: dns-helper
before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: default
    main: ./cmd/dns-helper/main.go
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_v{{ .Version }}"
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  draft: false
  name_template: 'v{{ .Version }}'
  extra_files:
    - glob: ./LICENSE
    - glob: ./README.md

brews:
  - name: dns-helper
    homepage: "https://github.com/musanmaz/dns-helper"
    description: "Cross-platform DNS switching and benchmarking tool"
    repository:
      owner: musanmaz
      name: homebrew-tap
    commit_author:
      name: "Mehmet Şirin Usanmaz"
      email: "mehmet@usanmaz.com"
    goarm: "6"
    test: |
      system "#{bin}/dns-helper", "--help"
